apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-rbac-permission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-version-manager
rules:
  - apiGroups:
      - '*'
    resources: ["pods","services","namespaces","deployments","jobs","statefulsets","statefulsets/scale"]
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-version-manager-binding
subjects:
  - kind: User
    name: cluster-admin-rbac-permission
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: service-version-manager
  apiGroup: rbac.authorization.k8s.io
