apiVersion: v1
kind: Service
metadata:
  name: reploy-webhook
spec:
  selector:
    io.kompose.service: k8s-reploy-webhook
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80